parameters:
    env(DATABASE_URL): '' # Allows cache:warmup to run if env is not loaded yet. Don't change.

doctrine:
    dbal:
        types:
            array_champions:  App\Util\Doctrine\ArrayChampions
        driver: 'pdo_pgsql'
        server_version: '5.7'
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
